### ISSUE TITLE
Jumlah sampah harusnya tidak ditambahkan sebelum proses transaksi selesai

### ISSUE THREAD

**Issue by andrikurniawan** [picklesquad/API#2]
@harventhy syuk, kita ada salah pas ngebuat API. harusnya jumlah sampah baru diupdate kalau si pengguna udah setuju sama transaksinya. Jadi pas di buat sama bank sampah belum ditambahin jumlah sampahnya selama belum disetujui proses transaksinya oleh pengguna

**Comment by ghost** [comment]
cantumin code nya dong ndri @andrikurniawan

**Comment by ghost** [comment]
Gini @andrikurniawan ndri, kan sampah usernya itu kita itung sendiri dari table transaksi kan, baru ditampilin di user profile. Mungkin maksud lo harusnya jumlah sampah yang ditampilih itu sampah yang statusnya udah disetujuin aja, iyha bukan?

**Comment by andrikurniawan** [comment]
ia syuk, itu maksud gue @harventhy hehe. belum kan?

**Comment by ghost** [comment]
Ok, gw ganti dulu ya, nanti gw push lagi kalo udah

**Comment by ghost** [comment]
Ohiya sekalian nih, saldo yg di user jadinya dipake aja ya. Jadi pas ada transaksi yang disetujuin, saldo usernya yang di table user ditambah. Kalo ada withdraw yang udah complete, saldo usernya yang di table user juga dikurang.

**Comment by ghost** [comment]
udah done ya, saldo user udah ketambah/kekurang kalo ada transaksi/withdraw. Sampah2 yang ditampilin juga udah diganti jadi cuma sampah yang udah disetujuin aja

**Comment by andrikurniawan** [comment]
sip, mantap syuk @harventhy 
gue close dulu ya case nya
